# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [8]:
print("numpy version is",np.__version__)
print("And the configuration is as follows")
print(np.show_config())

numpy version is 1.21.5
And the configuration is as follows
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\in

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [15]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [12]:
x=np.array([1,2,3,4,5])
print("Size of the array: ",x.size)
print("Memory size of one array element: ",x.itemsize)
print("Memory size of the numpy array: ",x.size*x.itemsize)

Size of the array:  5
Memory size of one array element:  4
Memory size of the numpy array:  20


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [14]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [19]:
v=np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [20]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [24]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [26]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [29]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [36]:
print(np.random.random((3,3,3)))

[[[0.98838394 0.05509961 0.69749006]
  [0.17119276 0.6804252  0.41242517]
  [0.13210917 0.11621367 0.94814285]]

 [[0.78175191 0.08507682 0.25128235]
  [0.9996408  0.18223836 0.48323041]
  [0.32655522 0.78334901 0.86007287]]

 [[0.90739662 0.32096371 0.32127788]
  [0.56261592 0.96895856 0.33496647]
  [0.92749573 0.64911085 0.47383261]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [48]:
x=np.random.random((10,10))
print(x)
print("Greatest Value: ",x.max())
print("Smallest Value: ",x.min())

[[0.62364756 0.04885769 0.27188088 0.20028407 0.97662576 0.87794087
  0.82443821 0.46839345 0.79449699 0.88663781]
 [0.63783127 0.65909742 0.38723483 0.53583808 0.29325693 0.02153454
  0.66045659 0.90146103 0.07811793 0.3979249 ]
 [0.25946051 0.52376818 0.19673312 0.75143072 0.5971768  0.84358363
  0.62260169 0.95232624 0.24335177 0.56083075]
 [0.29174447 0.91680581 0.03581103 0.65511086 0.15301009 0.54948879
  0.52376527 0.38682411 0.82008717 0.41268096]
 [0.39991685 0.39861921 0.15381295 0.20903857 0.55129813 0.90542516
  0.85090003 0.55676756 0.0745296  0.15526597]
 [0.20513651 0.79242586 0.64125291 0.90957309 0.29014056 0.02721194
  0.97001676 0.16265972 0.1283509  0.49529422]
 [0.72528416 0.53146885 0.73903928 0.71683677 0.22618479 0.38655243
  0.73340782 0.07390749 0.61621779 0.09475262]
 [0.0269621  0.22566317 0.8869499  0.96964934 0.54615126 0.99498011
  0.47866776 0.78603075 0.61291092 0.18515161]
 [0.76195201 0.51229578 0.09807486 0.04433885 0.90895527 0.13248166
  0.9861984 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [47]:
x=np.random.random(30)
print(x)
print("Mean: ",x.mean())

[0.27729141 0.22938434 0.53688835 0.3347473  0.95609826 0.6605327
 0.20710053 0.62598612 0.6321614  0.58694814 0.28032886 0.63413508
 0.57932228 0.37072281 0.76708556 0.55872708 0.40189786 0.46570188
 0.49496812 0.90206307 0.13540248 0.36609138 0.29399746 0.952491
 0.34892626 0.0504489  0.37531642 0.16803735 0.00745526 0.50977075]
Mean:  0.4570009467296759


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [76]:
x=np.ones((5,5),dtype=int)
x[1:-1,1:-1]=0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [75]:
x=np.ones((3,3),dtype=int)
print(np.pad(x,pad_width=1,mode='constant',constant_values=0))

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [64]:
print("0 * np.nan: ",0 * np.nan)
print("np.nan == np.nan: ",np.nan == np.nan)
print("np.inf > np.nan: ",np.inf > np.nan)
print("np.nan - np.nan: ",np.nan - np.nan)
print("0.3 == 3 * 0.1: ",0.3 == 3 * 0.1)

0 * np.nan:  nan
np.nan == np.nan:  False
np.inf > np.nan:  False
np.nan - np.nan:  nan
0.3 == 3 * 0.1:  False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [66]:
x=np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [74]:
x=np.zeros((8,8),dtype=int
          )
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [78]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [80]:
print(np.tile(np.array([[0,1],[1,0]]),(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [81]:
z=np.random.random((5,5))
z=(z-z.min())/(z.max()-z.min())
print(z)

[[0.70150065 0.99306053 0.63846953 0.         0.89243623]
 [0.19408406 0.92961535 0.4933005  0.26522568 0.90338929]
 [0.24694904 0.75180918 0.13377078 1.         0.64091046]
 [0.2446064  0.66968056 0.67860545 0.99777448 0.30681882]
 [0.39707924 0.71332196 0.71685559 0.23533454 0.55068128]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [87]:
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\Lingraj\AppData\Local\Temp\ipykernel_3812\169687878.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [94]:
print(np.dot(np.ones((5,3),dtype=int),np.ones((3,2),dtype=int)))

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [102]:
z=np.arange(11)
print("Original array is: ",z)
z[(z>3) & (z<8)]*=-1
print("Negated elements of array is: ",z)

Original array is:  [ 0  1  2  3  4  5  6  7  8  9 10]
Negated elements of array is:  [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [103]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [119]:
Z=np.arange(10)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[0 1 2 3 4 5 6 7 8 9]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [114]:
#print(np.array(0) / np.array(0))
#print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [136]:
z=np.random.uniform(-10,+10,10)
print(z)
print(np.copysign(np.ceil(np.abs(z)),z))

[-1.47181836  3.97958304  2.33229271 -2.53113395 -6.28667319 -9.679731
 -5.37607184 -8.68757462 -3.51936642 -7.65700827]
[ -2.   4.   3.  -3.  -7. -10.  -6.  -9.  -4.  -8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [135]:
z1=np.random.randint(0,10,10)
print(z1)
z2=np.random.randint(0,10,10)
print(z2)
print(np.intersect1d(z1,z2))

[3 9 1 2 6 2 9 8 7 6]
[2 2 6 8 6 5 8 6 3 1]
[1 2 3 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [12]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [11]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\Lingraj\AppData\Local\Temp\ipykernel_948\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [141]:
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1))

2022-06-27
2022-06-28
2022-06-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [142]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [143]:
A = -10
B = 20
z = ((A+B)*(-A/2))
print(z)

B = np.add(A,B)
A = np.divide(A,2)
A = np.negative(A)
A = np.multiply(A,B)
print(A)

50.0
50.0


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [7]:
Z = np.random.uniform(0,10,10)
print(Z)
print (Z-Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[5.90810423 6.87881083 2.58958432 6.94820729 0.11183686 1.76156295
 9.42275626 6.30474792 0.89096871 8.85094953]
[5. 6. 2. 6. 0. 1. 9. 6. 0. 8.]
[5. 6. 2. 6. 0. 1. 9. 6. 0. 8.]
[5. 6. 2. 6. 0. 1. 9. 6. 0. 8.]
[5 6 2 6 0 1 9 6 0 8]
[5. 6. 2. 6. 0. 1. 9. 6. 0. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [138]:
z=np.zeros((5,5),dtype=int)
z+=np.arange(5)
print(z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [191]:
def generate():
    for x in range(1,11):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[ 1  2  3  4  5  6  7  8  9 10]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [193]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [196]:
z = np.random.uniform(10,50,10)
print(z.astype(int))
z.sort()
print(z.astype(int))

[36 12 49 18 47 20 24 19 43 44]
[12 18 19 20 24 36 43 44 47 49]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [200]:
z = np.arange(10)
print(z)
print(np.sum(z))
print(np.add.reduce(z))

[0 1 2 3 4 5 6 7 8 9]
45
45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [206]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
equal = np.allclose(A,B)
print(equal)
equal1 = np.array_equal(A,B)
print(equal1)

[1 0 1 1 1] [0 0 0 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [210]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1
print(Z)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [214]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.53295205 0.73777911 0.44450558 1.17989069 0.81701372 0.74784367
 0.59559098 0.5931244  1.23222745 0.93477442]
[0.01425481 0.10252835 0.53253589 0.61302203 1.30380946 0.28456095
 0.85541489 0.07109642 0.88911327 1.50449239]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [217]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.18447918 0.44313546 0.65891563 0.9405108  0.56930119 0.7401751
 0.59436441 0.56176633 0.86995422 0.3947989 ]
[0.18447918 0.44313546 0.65891563 0.         0.56930119 0.7401751
 0.59436441 0.56176633 0.86995422 0.3947989 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [218]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [167]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [168]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [5]:
import numpy as np
my_array=np.arange(1001)
print(my_array)
np.set_printoptions(threshold=np.inf)
print(my_array)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [6]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

12


51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [3]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                 ('y', float, 1)]),                     
                  ('color',    [ ('r', float, 1),                                    
                                ('g', float, 1),                                   
                                ('b', float, 1)])]) 
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Lingraj\AppData\Local\Temp\ipykernel_11344\172073509.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [4]:
import numpy as np
Z = np.linspace((1,1),(3,3),3)
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[1. 1.]
 [2. 2.]
 [3. 3.]]
[[0.         1.41421356 2.82842712]
 [1.41421356 0.         1.41421356]
 [2.82842712 1.41421356 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [5]:
Z = (np.random.rand(3)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)
print(Y.base is Z)

[89.35083 81.81132 29.22396]
[89 81 29]
True


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [7]:
from io import StringIO
s = StringIO('''
1, 2, 3, 4, 5
6,  ,  , 7, 8
,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [8]:
Z = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [9]:
X, Y = np.meshgrid(np.linspace(-1,1,4), np.linspace(-1,1,5))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G.shape)
print(G)

(5, 4)
[[0.36787944 0.57375342 0.57375342 0.36787944]
 [0.53526143 0.8348063  0.8348063  0.53526143]
 [0.60653066 0.94595947 0.94595947 0.60653066]
 [0.53526143 0.8348063  0.8348063  0.53526143]
 [0.36787944 0.57375342 0.57375342 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [10]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p , replace= False),1)
print(Z)

print(np.random.choice(range(n*n), p))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[24 70 12]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [11]:
X = np.random.rand(5,10)
print(X)
Y = X - X.mean(axis = 1, keepdims = True)
print(Y)
Y = X - X.mean(axis=1).reshape(-1,1)
print(Y)

[[0.16418819 0.631057   0.40463451 0.74013918 0.81754718 0.85821711
  0.27014725 0.9986811  0.844368   0.96011248]
 [0.05882458 0.47650166 0.26572789 0.71300119 0.23185891 0.98228352
  0.86761951 0.37359802 0.45764937 0.7374992 ]
 [0.827798   0.09785561 0.48857111 0.60079197 0.56613579 0.01673196
  0.47187255 0.73564648 0.37927337 0.08897154]
 [0.02632799 0.60860002 0.35751099 0.14376949 0.82453256 0.66593173
  0.44350676 0.44950447 0.5151782  0.71063646]
 [0.13950883 0.56516872 0.19774802 0.59231974 0.98385578 0.28246508
  0.21050586 0.00834279 0.63649969 0.72763904]]
[[-0.50472101 -0.0378522  -0.26427469  0.07122998  0.14863798  0.18930791
  -0.39876195  0.3297719   0.17545879  0.29120328]
 [-0.4576318  -0.03995472 -0.2507285   0.19654481 -0.28459748  0.46582713
   0.35116312 -0.14285837 -0.05880702  0.22104282]
 [ 0.40043316 -0.32950922  0.06120627  0.17342714  0.13877095 -0.41063288
   0.04450771  0.30828164 -0.04809147 -0.33839329]
 [-0.44822188  0.13405015 -0.11703887 -0.33078037

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [12]:
data = np.random.randint(0,10,(3,3))
print(data)
print(data[data[:,1].argsort()])

[[0 1 4]
 [8 8 6]
 [2 3 0]]
[[0 1 4]
 [2 3 0]
 [8 8 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [13]:
data = np.random.randint(0,10,(3,3))
print((~data.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [14]:
data = np.random.uniform(0,1,10)
print(data)
z = 0.5
print(np.abs(data-z))
print(np.abs(data-z).argmin())
m = data.flat[np.abs(data-z).argmin()]
print(m)

[0.15058028 0.34364546 0.14001476 0.85739053 0.593806   0.50391858
 0.51493695 0.9262889  0.93045972 0.07349054]
[0.34941972 0.15635454 0.35998524 0.35739053 0.093806   0.00391858
 0.01493695 0.4262889  0.43045972 0.42650946]
5
0.5039185805422951


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [15]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A, B)

it = np.nditer([A,B, None])

for x,y,z in it:
    z[...] = x+y

print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [16]:
class NameArray(np.ndarray):
    def __new__(cls, array, name ="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj,'name','no name')
data = NameArray(np.arange(10),'range_10')
print(data.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [17]:
data = np.ones(10)
I = np.random.randint(0, len(Z), 20)
print(I)

data += np.bincount(I, minlength = len(Z))
print(data)

np.add.at(data,I,1)
print(data)

[4 8 2 0 4 7 4 5 3 8 6 4 1 9 6 3 0 8 3 6]
[3. 2. 2. 4. 5. 2. 4. 2. 4. 2.]
[5. 3. 3. 7. 9. 3. 7. 3. 7. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [18]:
A = [1,2,3,4,5,6]
B = [1,3,9,3,4,1]
C = np.bincount(B,A)
print(C)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [19]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]* 256 + I[...,2]
n = len(np.unique(F))
print(n)
print(np.unique(I))

8
[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [20]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis= (-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1, )).sum(axis = -1)
print(sum)

[[49 72 59 37]
 [61 74 33 57]
 [61 61 48 65]]
[[49 72 59 37]
 [61 74 33 57]
 [61 61 48 65]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [21]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts

import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.515670
1    0.407859
2    0.493930
3    0.536821
4    0.465687
5    0.518279
6    0.495454
7    0.486921
8    0.468835
9    0.459198
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [22]:
import numpy as np
A= np.random.uniform(0,1,(5,5))
B= np.random.uniform(0,1,(5,5))

print(np.diag(np.dot(A,B)))
print(np.sum(A * B.T, axis = 1))
print(np.einsum("ij,ji->i",A,B))

[1.13598116 1.43913805 1.33274261 1.19684053 1.11603554]
[1.13598116 1.43913805 1.33274261 1.19684053 1.11603554]
[1.13598116 1.43913805 1.33274261 1.19684053 1.11603554]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [23]:
Z = np.array([1,2,3,4,5])
nz = 3
z0 = np.zeros(len(Z) + (len(Z)-1)*(nz)) 
z0[::nz+1] = Z
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [24]:
A = np.ones((5,5,3))
print(A)
B = 2 * np.ones((5,5))
print(B)
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [25]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [26]:
faces = np.random.randint(0,100,(10,3))
print(faces)
F = np.roll(faces.repeat(2, axis = 1), -1, axis = 1)
print(F)
F = F.reshape(len(F) * 3, 2)
print(F)
F = np.sort(F, axis = 1)
print(F)
G = F.view(dtype = [('p0', F.dtype),('p1',F.dtype)])
print(G)
G = np.unique(G)
print(G)

[[17 63 29]
 [44 46 57]
 [86 56 49]
 [89 97 22]
 [25 53 66]
 [10  5 33]
 [15 35 40]
 [17 47 45]
 [67 24 57]
 [70 22  7]]
[[17 63 63 29 29 17]
 [44 46 46 57 57 44]
 [86 56 56 49 49 86]
 [89 97 97 22 22 89]
 [25 53 53 66 66 25]
 [10  5  5 33 33 10]
 [15 35 35 40 40 15]
 [17 47 47 45 45 17]
 [67 24 24 57 57 67]
 [70 22 22  7  7 70]]
[[17 63]
 [63 29]
 [29 17]
 [44 46]
 [46 57]
 [57 44]
 [86 56]
 [56 49]
 [49 86]
 [89 97]
 [97 22]
 [22 89]
 [25 53]
 [53 66]
 [66 25]
 [10  5]
 [ 5 33]
 [33 10]
 [15 35]
 [35 40]
 [40 15]
 [17 47]
 [47 45]
 [45 17]
 [67 24]
 [24 57]
 [57 67]
 [70 22]
 [22  7]
 [ 7 70]]
[[17 63]
 [29 63]
 [17 29]
 [44 46]
 [46 57]
 [44 57]
 [56 86]
 [49 56]
 [49 86]
 [89 97]
 [22 97]
 [22 89]
 [25 53]
 [53 66]
 [25 66]
 [ 5 10]
 [ 5 33]
 [10 33]
 [15 35]
 [35 40]
 [15 40]
 [17 47]
 [45 47]
 [17 45]
 [24 67]
 [24 57]
 [57 67]
 [22 70]
 [ 7 22]
 [ 7 70]]
[[(17, 63)]
 [(29, 63)]
 [(17, 29)]
 [(44, 46)]
 [(46, 57)]
 [(44, 57)]
 [(56, 86)]
 [(49, 56)]
 [(49, 86)]
 [(89, 97)]
 [(22,

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [27]:
A= np.bincount([1,1,2,3,4,4,6])
print(A)
B = np.repeat(np.arange(len(A)),A)
print(B)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [28]:
def average(a, n = 3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:]- ret[:-n]
    return ret[n-1:] / n
data = np.arange(20)
print(data)
print(average(data, n = 3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [30]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window +1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape = shape, strides = strides)

data = rolling(np.arange(10),3)
print(data)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [31]:
data = np.random.randint(0,2,100)
print(data)

print(np.logical_not(data, out = data))

data = np.random.uniform(-1.0, 1.0, 100)
print(data)

print(np.negative(data, out = data))

[0 1 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 0 0 0 0 1
 0 1 0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 1 1
 1 0 1 0 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 1 0 1 1 1]
[1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 1 1 1 1 0
 1 0 1 1 1 0 0 0 0 1 0 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0
 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0]
[ 0.29904765  0.44232963  0.24825538 -0.56859944 -0.98486208 -0.80783422
  0.16469741 -0.27593755 -0.50321535 -0.03711053 -0.92748148  0.7459488
  0.11627868 -0.74909031  0.71254059  0.77642205  0.51123226 -0.08855907
 -0.44562413 -0.13452066 -0.30477161  0.82380864  0.41404605  0.93269377
 -0.78316351  0.41162981 -0.44483143  0.5786662  -0.2939167  -0.31822942
 -0.08042097 -0.09043015 -0.76680743  0.41964197 -0.97979815  0.88168846
 -0.09591681  0.02371702  0.49635258 -0.52876136  0.76628211 -0.74392152
  0.78833036 -0.45207954 -0.64365473  0.78136119  0.58339244 -0.54801387
  0.91326

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [32]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U*T - p
    return np.sqrt((D **2).sum(axis = 1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print(distance(P0, P1, p))

[ 0.29945683  1.68171874  2.71084688  5.61734431  0.37653673  2.52681283
  6.73420395 12.41361659  2.2441256   4.845897  ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [33]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 10,2))
print(np.array([distance(P0,P1, p_i) for p_i in p]))

[[1.70740073e+00 2.47449310e+00 1.15996362e+01 2.55528129e-02
  7.51446755e+00 7.61251611e+00 1.22472114e+00 1.38648637e+01
  3.11989488e+00 9.85471294e-01]
 [1.68553837e-01 1.75935253e+00 1.08652946e+01 5.13596758e+00
  2.32377283e+00 4.60287420e+00 1.48888045e+00 8.71651916e+00
  5.05807891e-01 5.80941097e+00]
 [9.81713436e-01 1.41606617e+00 1.19746225e+01 4.71747104e-01
  7.01004418e+00 7.57828765e+00 1.24746240e+00 1.33707700e+01
  2.96281135e+00 8.46044515e-02]
 [8.92320871e+00 8.36914695e+00 4.31153624e+00 4.58726851e+00
  2.93973705e+00 1.11779575e+00 5.42867154e+00 9.23500182e+00
  2.98063769e+00 1.09344398e+00]
 [1.09760693e+01 5.39408490e+00 1.33852213e+00 1.55033900e+01
  7.99844638e+00 7.59796784e+00 1.37798078e+01 1.67105581e+00
  1.24156601e+01 9.45889035e+00]
 [8.62823328e-03 1.17599102e+00 1.33840375e+01 1.29574780e+00
  8.77632613e+00 9.27327560e+00 2.91497536e+00 1.51387844e+01
  4.70380181e+00 1.16306410e+00]
 [1.32062141e+01 7.94929600e+00 3.02716179e+00 1.54150285e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [34]:
Z = np.random.randint(0, 10, (10,10))
print(Z)
shape = (5,5)
fill = 0
position = (1,1)
R = np.ones(shape)
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2) + Rs%2

R_start = (R_start-np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = (np.maximum(R_start,(R_stop-np.maximum(Z_stop-Zs,0)))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 1 5 9 0 8 3 3 5 2]
 [8 5 6 6 1 3 4 9 0 6]
 [6 0 3 4 8 6 2 1 1 1]
 [0 0 6 1 3 1 8 0 4 0]
 [6 4 2 7 0 6 2 3 2 8]
 [7 6 0 1 5 5 2 5 6 8]
 [9 0 2 7 4 8 4 2 0 1]
 [9 3 2 1 5 2 2 4 3 3]
 [1 7 3 5 4 4 4 3 2 3]
 [3 5 9 5 0 9 9 2 5 0]]
[[7 1 5 9 0 8 3 3 5 2]
 [8 5 6 6 1 3 4 9 0 6]
 [6 0 3 4 8 6 2 1 1 1]
 [0 0 6 1 3 1 8 0 4 0]
 [6 4 2 7 0 6 2 3 2 8]
 [7 6 0 1 5 5 2 5 6 8]
 [9 0 2 7 4 8 4 2 0 1]
 [9 3 2 1 5 2 2 4 3 3]
 [1 7 3 5 4 4 4 3 2 3]
 [3 5 9 5 0 9 9 2 5 0]]
[[1. 1. 1. 1. 1.]
 [1. 7. 1. 5. 9.]
 [1. 8. 5. 6. 6.]
 [1. 6. 0. 3. 4.]
 [1. 0. 0. 6. 1.]]


C:\Users\Lingraj\AppData\Local\Temp\ipykernel_11344\3053161356.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [35]:
from numpy.lib import stride_tricks
Z = np.arange(1,15, dtype = np.uint32)
print(Z)
R = stride_tricks.as_strided(Z, (11,4), (4,4))
print(R)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [36]:
Z = np.random.uniform(0,1,(10,10))
U,S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [37]:
data = np.random.randint(0,10,50)
print(data)
print(np.bincount(data))
print(np.bincount(data).argmax())

[1 6 7 2 4 1 7 0 4 5 9 1 7 1 0 1 7 1 1 2 0 3 1 3 4 5 0 4 3 0 2 8 0 7 5 7 8
 7 4 5 3 3 2 4 1 2 7 5 5 0]
[7 9 5 5 6 6 1 8 2 1]
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [38]:
data = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (data.shape[0]-3)
j = 1 + (data.shape[1]-3)
C = stride_tricks.as_strided(data, shape= (i,j,n,n), strides = data.strides+ data.strides)
print(C)

[[[[3 4 4]
   [1 3 4]
   [1 0 4]]

  [[4 4 3]
   [3 4 2]
   [0 4 1]]

  [[4 3 1]
   [4 2 1]
   [4 1 2]]

  [[3 1 1]
   [2 1 1]
   [1 2 3]]

  [[1 1 1]
   [1 1 3]
   [2 3 2]]

  [[1 1 2]
   [1 3 3]
   [3 2 1]]

  [[1 2 2]
   [3 3 2]
   [2 1 1]]

  [[2 2 0]
   [3 2 1]
   [1 1 2]]]


 [[[1 3 4]
   [1 0 4]
   [1 3 2]]

  [[3 4 2]
   [0 4 1]
   [3 2 4]]

  [[4 2 1]
   [4 1 2]
   [2 4 4]]

  [[2 1 1]
   [1 2 3]
   [4 4 2]]

  [[1 1 3]
   [2 3 2]
   [4 2 4]]

  [[1 3 3]
   [3 2 1]
   [2 4 1]]

  [[3 3 2]
   [2 1 1]
   [4 1 2]]

  [[3 2 1]
   [1 1 2]
   [1 2 4]]]


 [[[1 0 4]
   [1 3 2]
   [0 3 4]]

  [[0 4 1]
   [3 2 4]
   [3 4 1]]

  [[4 1 2]
   [2 4 4]
   [4 1 2]]

  [[1 2 3]
   [4 4 2]
   [1 2 3]]

  [[2 3 2]
   [4 2 4]
   [2 3 0]]

  [[3 2 1]
   [2 4 1]
   [3 0 1]]

  [[2 1 1]
   [4 1 2]
   [0 1 2]]

  [[1 1 2]
   [1 2 4]
   [1 2 2]]]


 [[[1 3 2]
   [0 3 4]
   [1 2 1]]

  [[3 2 4]
   [3 4 1]
   [2 1 4]]

  [[2 4 4]
   [4 1 2]
   [1 4 1]]

  [[4 4 2]
   [1 2 3]
   [4 1 2]]

  [[4 2 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [39]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
        
def symetric(Z):
    return np.asarray(Z+Z.T-np.diag(Z.diagonal())).view(Symetric)

S= symetric(np.random.randint(0,10,(5,5)))
S[2,3]  = 42
print(S)

[[ 0 13 14  5 13]
 [13  4  6  5 13]
 [14  6  2 42  1]
 [ 5  5 42  4  6]
 [13 13  1  6  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [40]:
p, n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M,V, axes = [[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [41]:
Z = np.ones((16,16))
print(Z)
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0,Z.shape[0],k), axis = 0), np.arange(0,Z.shape[1], k), axis = 1)
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [42]:
def iterate(Z):
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:]+ Z[1:-1, 0:-2] + Z[1:-1, 2:]+Z[2:,0:-2]+ Z[2:, 1:-1]+ Z[2:,2:])

    birth = (N == 3) * (Z[1:-1, 1:-1] ==0)
    survive = ((N == 2)|(N ==3))& (Z[1:-1, 1:-1]==1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] =1
    return Z

Z = np.random.randint(0,2, (50,50))
for i in range(100):
    Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [43]:
ata = np.arange(10000)
print(data)
np.random.shuffle(data)
n = 5
print(data[np.argsort(data)[-n:]])
print(data[np.argpartition(-data,n )[:n]])

[[3 4 4 3 1 1 1 2 2 0]
 [1 3 4 2 1 1 3 3 2 1]
 [1 0 4 1 2 3 2 1 1 2]
 [1 3 2 4 4 2 4 1 2 4]
 [0 3 4 1 2 3 0 1 2 2]
 [1 2 1 4 1 2 3 0 4 2]
 [0 4 0 4 0 3 4 0 4 1]
 [0 4 3 0 1 3 1 1 1 4]
 [4 3 3 3 3 2 1 3 3 4]
 [4 1 2 2 3 2 4 2 0 2]]
[[[0 4 3 0 1 3 1 1 1 4]
  [0 4 0 4 0 3 4 0 4 1]
  [1 3 2 4 4 2 4 1 2 4]
  [4 1 2 2 3 2 4 2 0 2]
  [1 0 4 1 2 3 2 1 1 2]
  [4 3 3 3 3 2 1 3 3 4]
  [1 3 4 2 1 1 3 3 2 1]
  [3 4 4 3 1 1 1 2 2 0]
  [0 3 4 1 2 3 0 1 2 2]
  [1 2 1 4 1 2 3 0 4 2]]

 [[0 4 3 0 1 3 1 1 1 4]
  [1 2 1 4 1 2 3 0 4 2]
  [1 0 4 1 2 3 2 1 1 2]
  [4 1 2 2 3 2 4 2 0 2]
  [1 3 4 2 1 1 3 3 2 1]
  [0 3 4 1 2 3 0 1 2 2]
  [3 4 4 3 1 1 1 2 2 0]
  [1 3 2 4 4 2 4 1 2 4]
  [0 4 0 4 0 3 4 0 4 1]
  [4 3 3 3 3 2 1 3 3 4]]

 [[4 3 3 3 3 2 1 3 3 4]
  [3 4 4 3 1 1 1 2 2 0]
  [1 2 1 4 1 2 3 0 4 2]
  [1 3 2 4 4 2 4 1 2 4]
  [0 3 4 1 2 3 0 1 2 2]
  [4 1 2 2 3 2 4 2 0 2]
  [1 3 4 2 1 1 3 3 2 1]
  [1 0 4 1 2 3 2 1 1 2]
  [0 4 3 0 1 3 1 1 1 4]
  [0 4 0 4 0 3 4 0 4 1]]

 [[0 4 0 4 0 3 4 0 4 1]
  [0 3 4 1 2 3 0 1 

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [44]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype = int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:,n ] = arrays[n][ix[:,n]]
    return ix
print(cartesian(([1,2,3],[4,5],[6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [45]:
data = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(data.T, names='col1, col2, col3', formats='S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [46]:
x = np.random.rand(int(5e1))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.67 µs ± 286 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.11 µs ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
3.75 µs ± 308 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [47]:
A = np.random.randint(0, 5, (8,3))
B = np.random.randint(0, 5, (2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [48]:
data = np.random.randint(0,5,(10,3))
print(data)
E = np.all(data[:,1:] == data[:,:-1], axis = 1)
print(E)
U = data[~E]
print(U)

U = data[data.max(axis=1) != data.min(axis =1),:]
print(U)

[[1 1 1]
 [2 1 2]
 [2 1 2]
 [2 4 2]
 [2 1 2]
 [2 0 3]
 [2 1 0]
 [4 2 3]
 [2 3 3]
 [3 1 3]]
[ True False False False False False False False False False]
[[2 1 2]
 [2 1 2]
 [2 4 2]
 [2 1 2]
 [2 0 3]
 [2 1 0]
 [4 2 3]
 [2 3 3]
 [3 1 3]]
[[2 1 2]
 [2 1 2]
 [2 4 2]
 [2 1 2]
 [2 0 3]
 [2 1 0]
 [4 2 3]
 [2 3 3]
 [3 1 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [49]:
I = np.array([0,1,2,3,15,16,32,64,128])
print(I)
B = ((I.reshape(-1, 1) & (2 ** np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0,1,2,3,15,16,32,64,128], dtype = np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis = 1))

[  0   1   2   3  15  16  32  64 128]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [50]:
data = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(data).view(np.dtype((np.void, data.dtype.itemsize * data.shape[1])))
_, idx = np.unique(T, return_index = True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis = 0)
print(uZ)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [56]:
A = np.random.uniform(0,1 , 10)
print(A)
B = np.random.uniform(0,1,10)
print(B)

print(np.einsum('i->', A)) #np.sum(A)
print(np.einsum('i,i->i', A,B))# A * B
print(np.einsum('i,i', A,B))# np.inner(A, B)
print(np.einsum('i,j->ij', A,B))#np.outer(A, B)

A = [1,2,3]
B = [4,5,6]
print(np.inner(A, B))
# 1* 4+ 2* 5 + 3* 6
print(np.outer(A,B))
# 1   4, 5, 6 
# 2   4, 5, 6 
# 3   4, 5, 6

[0.42950911 0.74927028 0.58291982 0.1906299  0.25286735 0.52868129
 0.89190925 0.01117161 0.22336534 0.95408731]
[0.14388638 0.204952   0.73879525 0.31133124 0.78858771 0.43601508
 0.24172024 0.58539649 0.49259968 0.82132384]
4.8144112439766165
[0.06180051 0.15356444 0.43065839 0.05934904 0.19940809 0.23051301
 0.21559251 0.00653982 0.1100297  0.78361465]
2.251070173970912
[[0.06180051 0.08802875 0.31731929 0.1337196  0.3387056  0.18727245
  0.10382104 0.25143312 0.21157605 0.35276607]
 [0.10780979 0.15356444 0.55355732 0.23327125 0.59086533 0.32669314
  0.18111379 0.43862019 0.3690903  0.61539355]
 [0.08387422 0.11947058 0.43065839 0.18148115 0.4596834  0.25416183
  0.14090352 0.34123921 0.28714612 0.47876594]
 [0.02742905 0.03906998 0.14083647 0.05934904 0.1503284  0.08311751
  0.0460791  0.11159408 0.09390423 0.15656888]
 [0.03638417 0.05182567 0.1868172  0.07872551 0.19940809 0.11025398
  0.06112316 0.14802766 0.12456238 0.20768599]
 [0.07607004 0.10835429 0.39058722 0.164595   0.4

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [55]:
phi = np.arange(0, 10 * np.pi, 0.1)
a = 1
x = a* phi * np.cos(phi)
y = a* phi * np.sin(phi)
print(x)
dr = (np.diff(x) ** 2 + np.diff(y) ** 2) **.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)
print(r_int)
print(x_int)
print(y_int)
x = [1,3,6]
np.diff(x)

[  0.           0.09950042   0.19601332   0.28660095   0.3684244
   0.43879128   0.49520137   0.53538953   0.55736537   0.55944897
   0.54030231   0.49895573   0.43482931   0.34774848   0.237954
   0.1061058   -0.04671924  -0.21903564  -0.40896377  -0.61425018
  -0.83229367  -1.06017682  -1.29470246  -1.53243485  -1.76974492
  -2.00285904  -2.22791076  -2.44099478  -2.63822255  -2.81577868
  -2.96997749  -3.09731897  -3.19454328  -3.25868324  -3.28711385
  -3.27759841  -3.2283303   -3.13797012  -3.00567731  -2.83113599
  -2.61457448  -2.35677818  -2.05909545  -1.72343644  -1.35226463
  -0.9485811   -0.51590162  -0.05822672   0.41999512   0.91391061
   1.41831093   1.92768649   2.43628669   2.93818398   3.42734153
   3.89768376   4.34316892   4.75786287   5.1360132    5.47212274
   5.76102172   5.99793747   6.178561     6.29910941   6.35638348
   6.34781957   6.27153511   6.12636709   5.91190293   5.62850319
   5.27731578   4.86028133   4.38012946   3.84036588   3.24525022
   2.59976488

array([2, 3])

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [53]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X,1)==0, axis = -1)
print(M)
M &= (X.sum(axis = -1) == n)
print(X[M])

[ True  True False]
[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [51]:
X = np.random.randn(100)
print(x)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
print(idx)
means = X[idx].mean(axis = 1)
print(means)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[0.25533053 0.67982392 0.08804089 0.88054714 0.6386657  0.49032951
 0.78378656 0.97757692 0.90795784 0.14277536 0.13061141 0.96422444
 0.57900597 0.11023612 0.71477325 0.95764163 0.55178807 0.35496076
 0.07128944 0.79380158 0.03439341 0.87699502 0.89953957 0.19442642
 0.50307216 0.80996768 0.36407838 0.28164085 0.91854103 0.97413181
 0.19998629 0.44757453 0.37023188 0.95461332 0.35548579 0.29546292
 0.0751288  0.82067026 0.63211085 0.64969781 0.0989642  0.79464444
 0.58901632 0.11830149 0.93940963 0.9173018  0.74953022 0.1325279
 0.72580262 0.1128377 ]
[[60 20  0 ...  9 50 54]
 [80 97  8 ... 58 34 98]
 [38 59  7 ... 91 73 21]
 ...
 [61 93 38 ... 13 58 54]
 [ 1 74 76 ... 74 26 39]
 [62  1 62 ... 12 99 95]]
[-1.15250553e-01 -8.08867406e-02 -2.16540127e-02 -1.25329340e-01
 -1.16218889e-01 -1.21866657e-01 -5.49419068e-02 -2.69606785e-01
 -9.80742607e-02 -2.27235382e-01 -5.98669406e-02 -1.47958320e-01
  9.94476783e-02 -1.67603210e-01 -1.79893973e-02 -2.17955879e-01
  3.04006449e-02 -5.48449